apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fvil
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-fvil@sha256:b6cb69f8b140ec4ce049e80d71c9d422905e83c69fef60257815c3225b2da4b6
        name: my-nodejs
        resources: {}
status: {}
